# Generated by Django 5.0 on 2023-12-26 00:13

import django.db.models.deletion
import rollsocialnetwork.phone_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=rollsocialnetwork.phone_auth.models.fill_code,
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=rollsocialnetwork.phone_auth.models.fill_valid_until,
                        editable=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
