# Generated by Django 5.0.3 on 2024-03-25 14:42

import django.db.models.deletion
import rollsocialnetwork.phone_auth.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rollsocialnetwork.phone_auth.utils.fill_code, editable=False, max_length=8)),
                ('valid_until', models.DateTimeField(default=rollsocialnetwork.phone_auth.utils.fill_valid_until, editable=False)),
                ('attempts', models.PositiveIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
