# Generated by Django 5.0 on 2023-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="attempts",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
